### PR TITLE
Migrate to GH Actions

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #6

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think it's failing because in a Container there is no Snap...

**Comment by ronaldtse** [comment]
Changed to use GH Action for snap setup/login here: 6c3633932b4842c3ee3ba1504a35c7058952bbea

**Comment by ronaldtse** [comment]
Actually, reverting, will let you handle it 👍

**Comment by CAMOBAP** [comment]
@ronaldtse finally done, I will merge once last CI will be passed

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 !

**Pull request merged**
